cc_library(
    name = "test",
    hdrs = ["maxcommon.hpp",],
    srcs = ["maxcommon.cpp"],
    copts = ["-std=c++1z", "-Iexternal/gtest/include"],
    deps = ["@gtest//:main"],
    visibility = ["//visibility:public"]
)
