cc_library(
    name = "test",
    hdrs = [],
    srcs = [
            "arrays.cpp",
            "arrays.hpp",
            "stack9.cpp",
            "stack9.hpp",
            ],
    copts = ["-std=c++1z", "-Iexternal/gtest/include"],
    deps = ["@gtest//:main"],
    visibility = ["//visibility:public"]
)
