cc_library(
    name = "test",
    hdrs = [],
    srcs = ["is_homogeneous.cpp",
            "var_using.cpp",
            "print.hpp",
            "var_indices.cpp",
            ],
    copts = ["-std=c++1z", "-Iexternal/gtest/include"],
    deps = ["@gtest//:main"],
    visibility = ["//visibility:public"]
)
